import NavBar from "../components/Navbar";
import ToasterProvider from "../providers/ToastProvider";
import UserContextProvider from "../providers/UserContextProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <ToasterProvider />
          <NavBar />
          <main className="flex h-full md:h-screen py-24 sm:py-32 justify-center flex-col gap-5 md:gap-10 mx-5 md:mx-20 items-center">
            {children}
          </main>
        </UserContextProvider>
      </body>
    </html>
  );
}
